
management:
  info:
    git:
      mode: "full"
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: my.eins.InputChannel
        output:
          destination: my.eins.OutputChannel
      default-binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672

---

spring:
  profiles: vm
  cloud:
    stream:
      default-binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 0.0.0.0
                port: 5672
